# action.yml
name: 'Kube Helm deploy'
description: 'Kubernetes deploy by Helm'
branding:
  icon: 'check-square'
  color: 'white'
inputs:
  namespace:  # namespace to deploy
    description: 'namespace to deploy'
    required: true
    default: ''
  kube_auth_line:  # base64 dencoded kube config file
    description: 'base64 dencoded kube config file'
    required: true
    default: ''
  release_name:
    description: 'Chart release name'
    required: true
    default: ''
  env_name:
    description: 'Enviroment name'
    required: true
  prepare:
    description: 'Should be set to true if envsubst needed to apply to *.yaml'
    required: true
    default: 'false'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/black-magius/kube-helm:main'
  env:
    kube_helm_deploy_app_version: ""
    kube_helm_deploy_path_to_helm_files: "./.deploy/.chart"
    kube_helm_deploy_destination_namespace: ${{ inputs.namespace }}
    kube_helm_deploy_imagePullPolicy: ""
    kube_helm_deploy_kube_auth_line: ${{ inputs.kube_auth_line }}
    kube_helm_deploy_release_name: ${{ inputs.release_name }}
    kube_helm_deploy_value_file_name: "values-${{ inputs.env_name }}.yaml"
    kube_helm_deploy_prepare: ${{ inputs.prepare }}
  args:
    - ${{ inputs.namespace }}
